import assert from 'node:assert/strict';
export async function checkScout(context, panel, origin) {
  const send = message => panel.evaluate(message => chrome.runtime.sendMessage(message), message);
  const saved = await send({ type: 'profile.save', profile: { name: 'Scout fixture', positiveKeywords: ['scoutkeyword'], negativeKeywords: [] } });
  assert.equal(saved.ok, true);
  await send({ type: 'navigation.settings', eyeballLevel: 50, autoPauseColors: ['#ffe077'] });
  const settings = await context.newPage();
  await settings.goto(new URL('/options/index.html', panel.url()).href);
  await settings.waitForFunction(() => document.querySelector('#model').options.length > 0);
  const record = handle => ({ accountBasedIn: handle === 'matching' ? 'United States' : 'Canada', checkedAt: '2026-09-11T07:57:26.431Z', connectedVia: 'United States App Store', dateJoined: 'February 2025', followStatus: 'skipped', handle, note: 'Matches selected rule.', profileUrl: `https://x.com/${handle}`, status: 'checked' });
  const value = { version: 1, exportedAt: '2026-09-11T11:38:35.415Z', records: [record('matching'), record('other')] };
  await settings.locator('#scout-file').setInputFiles({ name: 'scout.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(value)) });
  await settings.getByText('Scout profiles uploaded. Location checks updated.', { exact: true }).waitFor();
  await settings.locator('#location-check-location').fill('United States');
  await settings.locator('#location-check-enabled').check();
  await settings.getByRole('button', { name: 'Save location check', exact: true }).click();
  await settings.getByText('Location check saved.', { exact: true }).waitFor();
  await settings.reload();
  await settings.waitForFunction(() => document.querySelector('#location-check-enabled').checked);
  assert.equal(await settings.locator('#location-check-location').inputValue(), 'United States');
  assert.equal(await settings.locator('#scout-summary').textContent(), '2 scout profiles uploaded.');
  await settings.locator('#scout-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{}') });
  await settings.locator('#status.error').waitFor();
  assert.deepEqual((await send({ type: 'state.get' })).data.scoutData, value);
  const site = await context.newPage();
  const post = (handle, id) => `<article id="${id}" style="height:650px"><div data-testid="User-Name"><a href="https://x.com/${handle}">${handle}</a></div><p>scoutkeyword <a href="https://x.com/matching">@matching</a></p><div role="link"><div data-testid="User-Name"><a href="https://x.com/matching">quoted</a></div></div></article>`;
  await site.route(`${origin}/scout`, route => route.fulfill({ contentType: 'text/html', body: `<!doctype html><body style="margin:0">${post('other', 'skip')}${post('unknown', 'unknown')}${post('matching', 'match')}<div style="height:2000px">End</div></body>` }));
  await site.goto(`${origin}/scout`);
  await site.bringToFront();
  await site.waitForFunction(() => CSS.highlights.get('spotadog-matches')?.size >= 3);
  const tabId = await panel.evaluate(async url => (await chrome.tabs.query({})).find(tab => tab.url === url).id, site.url());
  assert.equal((await send({ type: 'scroll.set', tabId, enabled: true, speed: 600, pauseAfterPositive: true })).ok, true);
  await panel.waitForFunction(() => document.querySelector('#scroll-status').textContent.includes('location verified: United States'));
  const offset = await site.evaluate(() => document.querySelector('#match').getBoundingClientRect().top - innerHeight / 2);
  assert.ok(Math.abs(offset) <= 1, JSON.stringify({ offset, scroll: (await send({ type: 'scroll.get', tabId })).data, config: (await send({ type: 'scan.get' })).data.locationCheck }));
  const position = await site.evaluate(() => scrollY);
  await send({ type: 'scroll.resume', tabId });
  await site.waitForFunction(y => scrollY > y + 50, position);
  await settings.getByRole('button', { name: 'Clear uploaded profiles', exact: true }).click();
  await settings.getByText('Scout profiles cleared.', { exact: true }).waitFor();
  assert.equal((await send({ type: 'state.get' })).data.scoutData.records.length, 0);
  await send({ type: 'scout.settings', settings: { enabled: false, location: '' } });
  await send({ type: 'profile.delete', id: saved.data.id });
  await site.close(); await settings.close();
}
